apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: localhost:5000/chatbot-sdk-backend:latest
          imagePullPolicy: Always
          command: ["node", "dist/main-worker"]
          envFrom:
            - configMapRef:
                name: chatbot-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: POSTGRES_PASSWORD
